#!/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2017-2018 ANSSI. All Rights Reserved.
# initiate and provide the default environment for all the scripts

CONFIG="$HOME/.sub-clip.json"

if ! test -e $CONFIG; then
    echo "Creating default configuration file"
    cp ${_CLIP_ROOT}/share/clip/default-env.json $CONFIG
fi

source <( python ${_CLIP_ROOT}/libexec/cffile-to-bash.py "$CONFIG")
